// <auto-generated />
namespace Hotel_MS.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class tblroom_type : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(tblroom_type));
        
        string IMigrationMetadata.Id
        {
            get { return "202112312025548_tblroom_type"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
